# Generated by Django 3.2.3 on 2021-05-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('valorLocacaoEquipamento', models.FloatField()),
                ('fotoEquipamento', models.ImageField(upload_to='')),
                ('horaDeUso', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'EQUIPAMENTO',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=50)),
                ('valorLocacaoEstudio', models.FloatField()),
                ('fotoEstudio', models.ImageField(upload_to='')),
                ('horaDeUso', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estúdio',
                'verbose_name_plural': 'ESTÚDIO',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'USUÁRIO',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipamento')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'PEDIDO',
            },
        ),
    ]
